stages:
  - build

build:
    image: ubuntu:20.04
    stage: build
    script:
    - echo "Configuring enviroment ..."
    - apt-get update -qq && apt-get install -y -qq gcc g++ cmake python3
    - echo "Building project ..."
    - make
